Issue 62: Ran Parquet Files
zazwaz12/CITS3200---National-Housing-Simulation pull request #63
Opened 2024-09-11 08:48 UTC by zazwaz12

---
Title: "Closes #62 "
---

# **Summary of Changes**
The file for converting Files to Parquet.

# **Checklist:**
- [x] My code follows the code style of this project.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests prove my fix is effective or that my feature works.
- [x] I have annotated added types appropriately.

2024-09-11 09:18 UTC, ctmes approved these changes
Looks great

2024-09-11 09:20 UTC, SodaVolcano requested changes

2024-09-11 09:20 UTC, SodaVolcano commented on scripts/spreadsheet_to_parquet.py
> +    output_dir = input_dir.replace("FilesIn", "AppStaging")
remove

2024-09-11 09:20 UTC, SodaVolcano commented on scripts/spreadsheet_to_parquet.py
> +
remove

2024-09-12 00:08 UTC, SodaVolcano approved these changes

2024-09-12 00:08 UTC, SodaVolcano commented
FYI I've extended the help message

2024-09-12 00:09 UTC, merged