Issue 75 make it possible for one person to have multiple censu
zazwaz12/CITS3200---National-Housing-Simulation pull request #80
Opened 2024-09-25 12:08 UTC by zazwaz12

---
Title: "Closes #75 "
---

# **Summary of Changes**
A function that takes in a dictionary of a census grouping occurences and their values, then returns a lazy frame with the sample proportion for valid simulation.

# **Checklist:**
- [X] My code follows the code style of this project.
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] New and existing unit tests prove my fix is effective or that my feature works.
- [X] I have annotated added types appropriately.

### **Additional context**
How this will work in will become more apparent once we have the classifications and categorization decided.

2024-09-26 04:42 UTC, ctmes approved these changes

2024-09-26 05:23 UTC, ctmes commented on nhs/data/allocation.py
> +
maybe a comment about how it works and why

2024-09-29 03:55 UTC, SodaVolcano requested changes
Yup good progress, though I'll ask you to finish #75 before making a PR since this PR seems to be unfinished

2024-09-29 03:55 UTC, SodaVolcano commented on nhs/data/allocation.py
> +    )
Could you do this without making another lazy frame? so append a new column onto the existing dataframe for example

2024-09-29 03:55 UTC, SodaVolcano commented on nhs/data/allocation.py
> +def calculate_proportions(group_values_dict: dict) -> pl.LazyFrame:
input should be a lazyframe as well and not a dictionary

2024-09-29 03:55 UTC, SodaVolcano commented on nhs/data/allocation.py
> +    print(lf.collect())
you can use `logger.debug()` instead of print

2024-09-29 03:56 UTC, SodaVolcano commented
See review comment above - try making a PR after adding the full feature for #75 , so far this PR only have proportion calculation

2024-09-29 03:56 UTC, closed without merging